package ru.igrakov.utils

/**
 * Объект для хранения и получения локализованных строк (текстов) интерфейса.
 * Поддерживает несколько языков (локалей) и предоставляет метод для получения текста по ключу.
 * @author Andrey Igrakov
 */
object Strings {
    // Текущая локаль (язык), используется для выбора набора строк.
    var locale = "ru"

    // Карта языков, где ключ — код языка (locale),
    // значение — карта ключей текстов к соответствующим переведённым строкам.
    private val strings = mapOf(
        "en" to mapOf(
            "workspaces" to "Workspaces",
            "new_workspace" to "New Workspace",
            "no_workspaces" to "There are no workspaces",
            "settings" to "Settings",
            "add_column" to "Add Column",
            "add_card" to "Add Card",
            "add" to "Add",
            "new_card" to "New Card",
            "new_column" to "New Column",
            "title_column" to "Title column",
            "title_workspace" to "Title workspace",
            "delete" to "Delete",
            "edit" to "Edit",
            "edit_card" to "Edit card",
            "save" to "Save",
            "back" to "Back",
            "theme" to "Theme",
            "theme_light" to "Light",
            "theme_dark" to "Dark",
            "select_folder" to "Select Folder",
            "path_folder" to "Folder path",
            "create" to "Create",
            "cancel" to "Cancel",
            "title" to "Title",
            "description" to "Description",
            "difficulty" to "Difficulty",
            "color_card" to "Card color",
            "delete_column" to "Delete column",
            "exit" to "Exit",
            "language" to "Language",
            "difficulty_easy" to "Easy",
            "difficulty_middle" to "Medium",
            "difficulty_hard" to "Hard",
            "app_name" to "Task Board",
            "welcome" to "Welcome",
            "loading" to "Loading...",
            "error" to "Error",
            "success" to "Success",
            "people" to "People",
            "add_person" to "Add person",
            "remove_person" to "Remove person",
            "edit_person" to "Edit person",
            "no_dedline" to "No deadline",
            "select_date" to "Select date",
            "mo" to "Mo",
            "tu" to "Tu",
            "we" to "We",
            "th" to "Th",
            "fr" to "Fr",
            "sa" to "Sa",
            "su" to "Su",
            "full_name" to "Full name",
            "remove" to "Remove",
            "dark_theme" to "Dark theme",
            "light_theme" to "Light theme"
        ),
        "ru" to mapOf(
            "workspaces" to "Рабочие пространства",
            "new_workspace" to "Новое пространство",
            "no_workspaces" to "Нет рабочих пространств",
            "settings" to "Настройки",
            "add_column" to "Добавить колонку",
            "add_card" to "Добавить карточку",
            "add" to "Добавить",
            "new_card" to "Новая карточка",
            "new_column" to "Новая колонка",
            "title_column" to "Название колонки",
            "title_workspace" to "Название пространства",
            "delete" to "Удалить",
            "edit" to "Редактировать",
            "edit_card" to "Редактировать карточку",
            "save" to "Сохранить",
            "back" to "Назад",
            "theme" to "Тема",
            "theme_light" to "Светлая",
            "theme_dark" to "Тёмная",
            "select_folder" to "Выбрать папку",
            "path_folder" to "Путь до папки",
            "create" to "Создать",
            "cancel" to "Отменить",
            "title" to "Название",
            "description" to "Описание",
            "difficulty" to "Сложность",
            "color_card" to "Цвет карточки",
            "delete_column" to "Удалить колонку",
            "exit" to "Выйти",
            "language" to "Язык",
            "difficulty_easy" to "Легко",
            "difficulty_middle" to "Средне",
            "difficulty_hard" to "Сложно",
            "app_name" to "Доска задач",
            "welcome" to "Добро пожаловать",
            "loading" to "Загрузка...",
            "error" to "Ошибка",
            "success" to "Успех",
            "people" to "Человек",
            "add_person" to "Добавить человека",
            "remove_person" to "Удалить человека",
            "edit_person" to "Изменить человека",
            "no_dedline" to "Нет срока",
            "select_date" to "Выбрать дату",
            "mo" to "Пн",
            "tu" to "Вт",
            "we" to "Ср",
            "th" to "Чт",
            "fr" to "Пт",
            "sa" to "Сб",
            "su" to "Вс",
            "full_name" to "ФИО",
            "remove" to "Удалить",
            "dark_theme" to "Тёмная тема",
            "light_theme" to "Белая тема"
        ),
        "es" to mapOf(
            "workspaces" to "Espacios de trabajo",
            "new_workspace" to "Nuevo espacio de trabajo",
            "no_workspaces" to "No hay espacios de trabajo",
            "settings" to "Configuración",
            "add_column" to "Añadir columna",
            "add_card" to "Añadir tarjeta",
            "add" to "Añadir",
            "new_card" to "Nueva tarjeta",
            "new_column" to "Nueva columna",
            "title_column" to "Título de columna",
            "title_workspace" to "Título del espacio",
            "delete" to "Eliminar",
            "edit" to "Editar",
            "edit_card" to "Editar tarjeta",
            "save" to "Guardar",
            "back" to "Atrás",
            "theme" to "Tema",
            "theme_light" to "Claro",
            "theme_dark" to "Oscuro",
            "select_folder" to "Seleccionar carpeta",
            "path_folder" to "Ruta de carpeta",
            "create" to "Crear",
            "cancel" to "Cancelar",
            "title" to "Título",
            "description" to "Descripción",
            "difficulty" to "Dificultad",
            "color_card" to "Color de tarjeta",
            "delete_column" to "Eliminar columna",
            "exit" to "Salir",
            "language" to "Idioma",
            "difficulty_easy" to "Fácil",
            "difficulty_middle" to "Medio",
            "difficulty_hard" to "Difícil",
            "app_name" to "Tablero de tareas",
            "welcome" to "Bienvenido",
            "loading" to "Cargando...",
            "error" to "Error",
            "success" to "Éxito",
            "people" to "Personas",
            "add_person" to "Añadir persona",
            "remove_person" to "Eliminar persona",
            "edit_person" to "Editar persona",
            "no_dedline" to "Sin fecha límite",
            "select_date" to "Seleccionar fecha",
            "mo" to "Lu",
            "tu" to "Ma",
            "we" to "Mi",
            "th" to "Ju",
            "fr" to "Vi",
            "sa" to "Sa",
            "su" to "Do",
            "full_name" to "Nombre completo",
            "remove" to "Eliminar",
            "dark_theme" to "Tema oscuro",
            "light_theme" to "Tema claro"
        ),
        "fr" to mapOf(
            "workspaces" to "Espaces de travail",
            "new_workspace" to "Nouvel espace de travail",
            "no_workspaces" to "Aucun espace de travail",
            "settings" to "Paramètres",
            "add_column" to "Ajouter une colonne",
            "add_card" to "Ajouter une carte",
            "add" to "Ajouter",
            "new_card" to "Nouvelle carte",
            "new_column" to "Nouvelle colonne",
            "title_column" to "Titre de la colonne",
            "title_workspace" to "Titre de l'espace",
            "delete" to "Supprimer",
            "edit" to "Modifier",
            "edit_card" to "Modifier la carte",
            "save" to "Enregistrer",
            "back" to "Retour",
            "theme" to "Thème",
            "theme_light" to "Clair",
            "theme_dark" to "Sombre",
            "select_folder" to "Sélectionner un dossier",
            "path_folder" to "Chemin du dossier",
            "create" to "Créer",
            "cancel" to "Annuler",
            "title" to "Titre",
            "description" to "Description",
            "difficulty" to "Difficulté",
            "color_card" to "Couleur de la carte",
            "delete_column" to "Supprimer la colonne",
            "exit" to "Quitter",
            "language" to "Langue",
            "difficulty_easy" to "Facile",
            "difficulty_middle" to "Moyen",
            "difficulty_hard" to "Difficile",
            "app_name" to "Tableau de tâches",
            "welcome" to "Bienvenue",
            "loading" to "Chargement...",
            "error" to "Erreur",
            "success" to "Succès",
            "people" to "Personnes",
            "add_person" to "Ajouter une personne",
            "remove_person" to "Supprimer une personne",
            "edit_person" to "Modifier la personne",
            "no_dedline" to "Pas de date limite",
            "select_date" to "Sélectionner une date",
            "mo" to "Lu",
            "tu" to "Ma",
            "we" to "Me",
            "th" to "Je",
            "fr" to "Ve",
            "sa" to "Sa",
            "su" to "Di",
            "full_name" to "Nom complet",
            "remove" to "Supprimer",
            "dark_theme" to "Thème sombre",
            "light_theme" to "Thème clair"
        ),
        "de" to mapOf(
            "workspaces" to "Arbeitsbereiche",
            "new_workspace" to "Neuer Arbeitsbereich",
            "no_workspaces" to "Keine Arbeitsbereiche",
            "settings" to "Einstellungen",
            "add_column" to "Spalte hinzufügen",
            "add_card" to "Karte hinzufügen",
            "add" to "Hinzufügen",
            "new_card" to "Neue Karte",
            "new_column" to "Neue Spalte",
            "title_column" to "Spaltentitel",
            "title_workspace" to "Arbeitsbereichstitel",
            "delete" to "Löschen",
            "edit" to "Bearbeiten",
            "edit_card" to "Karte bearbeiten",
            "save" to "Speichern",
            "back" to "Zurück",
            "theme" to "Thema",
            "theme_light" to "Hell",
            "theme_dark" to "Dunkel",
            "select_folder" to "Ordner auswählen",
            "path_folder" to "Ordnerpfad",
            "create" to "Erstellen",
            "cancel" to "Abbrechen",
            "title" to "Titel",
            "description" to "Beschreibung",
            "difficulty" to "Schwierigkeit",
            "color_card" to "Kartenfarbe",
            "delete_column" to "Spalte löschen",
            "exit" to "Beenden",
            "language" to "Sprache",
            "difficulty_easy" to "Einfach",
            "difficulty_middle" to "Mittel",
            "difficulty_hard" to "Schwierig",
            "app_name" to "Aufgabenboard",
            "welcome" to "Willkommen",
            "loading" to "Wird geladen...",
            "error" to "Fehler",
            "success" to "Erfolg",
            "people" to "Personen",
            "add_person" to "Person hinzufügen",
            "remove_person" to "Person entfernen",
            "edit_person" to "Person bearbeiten",
            "no_dedline" to "Keine Frist",
            "select_date" to "Datum auswählen",
            "mo" to "Mo",
            "tu" to "Di",
            "we" to "Mi",
            "th" to "Do",
            "fr" to "Fr",
            "sa" to "Sa",
            "su" to "So",
            "full_name" to "Vollständiger Name",
            "remove" to "Entfernen",
            "dark_theme" to "Dunkles Thema",
            "light_theme" to "Helles Thema"
        )
    )

    /**
     * Возвращает строку для текущей локали по ключу.
     * Если ключ не найден, возвращает сам ключ (для отладки).
     *
     * @param key ключ строки
     * @return локализованная строка или ключ, если перевод отсутствует
     */
    fun t(key: String) = strings[locale]?.get(key) ?: key
}
