package ru.igrakov.utils

/**
 * @author Andrey Igrakov
 */
object Strings {
    var locale = "ru"

    private val strings = mapOf(
        "en" to mapOf(
            "workspaces" to "Workspaces",
            "new_workspace" to "New Workspace",
            "no_workspaces" to "There are no workspaces",
            "settings" to "Settings",
            "add_column" to "Add Column",
            "add_card" to "Add Card",
            "add" to "Add",
            "new_card" to "New Card",
            "new_column" to "New Column",
            "title_column" to "Title column",
            "title_workspace" to "Title workspace",
            "delete" to "Delete",
            "edit" to "Edit",
            "edit_card" to "Edit card",
            "save" to "Save",
            "back" to "Back",
            "theme" to "Theme",
            "theme_light" to "Light",
            "theme_dark" to "Dark",
            "select_folder" to "Select Folder",
            "path_folder" to "Folder path",
            "create" to "Create",
            "cancel" to "Cancel",
            "title" to "Title",
            "description" to "Description",
            "difficulty" to "Difficulty",
            "color_card" to "Card color",
            "delete_column" to "Delete column",
            "exit" to "Exit",
            "language" to "Language",
            "difficulty_easy" to "Easy",
            "difficulty_middle" to "Medium",
            "difficulty_hard" to "Hard",
            "app_name" to "Task Board",
            "welcome" to "Welcome",
            "loading" to "Loading...",
            "error" to "Error",
            "success" to "Success"
        ),
        "ru" to mapOf(
            "workspaces" to "Рабочие пространства",
            "new_workspace" to "Новое пространство",
            "no_workspaces" to "Нет рабочих пространств",
            "settings" to "Настройки",
            "add_column" to "Добавить колонку",
            "add_card" to "Добавить карточку",
            "add" to "Добавить",
            "new_card" to "Новая карточка",
            "new_column" to "Новая колонка",
            "title_column" to "Название колонки",
            "title_workspace" to "Название пространства",
            "delete" to "Удалить",
            "edit" to "Редактировать",
            "edit_card" to "Редактировать карточку",
            "save" to "Сохранить",
            "back" to "Назад",
            "theme" to "Тема",
            "theme_light" to "Светлая",
            "theme_dark" to "Тёмная",
            "select_folder" to "Выбрать папку",
            "path_folder" to "Путь до папки",
            "create" to "Создать",
            "cancel" to "Отменить",
            "title" to "Название",
            "description" to "Описание",
            "difficulty" to "Сложность",
            "color_card" to "Цвет карточки",
            "delete_column" to "Удалить колонку",
            "exit" to "Выйти",
            "language" to "Язык",
            "difficulty_easy" to "Легко",
            "difficulty_middle" to "Средне",
            "difficulty_hard" to "Сложно",
            "app_name" to "Доска задач",
            "welcome" to "Добро пожаловать",
            "loading" to "Загрузка...",
            "error" to "Ошибка",
            "success" to "Успех"
        ),
        "es" to mapOf(
            "workspaces" to "Espacios de trabajo",
            "new_workspace" to "Nuevo espacio",
            "no_workspaces" to "No hay espacios de trabajo",
            "settings" to "Configuración",
            "add_column" to "Añadir columna",
            "add_card" to "Añadir tarjeta",
            "add" to "Añadir",
            "new_card" to "Nueva tarjeta",
            "new_column" to "Nueva columna",
            "title_column" to "Título de columna",
            "delete" to "Eliminar",
            "edit" to "Editar",
            "edit_card" to "Editar tarjeta",
            "save" to "Guardar",
            "back" to "Atrás",
            "theme" to "Tema",
            "theme_light" to "Claro",
            "theme_dark" to "Oscuro",
            "select_folder" to "Seleccionar carpeta",
            "path_folder" to "Ruta de carpeta",
            "create" to "Crear",
            "cancel" to "Cancelar",
            "title" to "Título",
            "description" to "Descripción",
            "difficulty" to "Dificultad",
            "color_card" to "Color de tarjeta",
            "delete_column" to "Eliminar columna",
            "exit" to "Salir",
            "language" to "Idioma",
            "difficulty_easy" to "Fácil",
            "difficulty_middle" to "Medio",
            "difficulty_hard" to "Difícil",
            "app_name" to "Tablero de tareas",
            "welcome" to "Bienvenido",
            "loading" to "Cargando...",
            "error" to "Error",
            "success" to "Éxito"
        ),
        "fr" to mapOf(
            "workspaces" to "Espaces de travail",
            "new_workspace" to "Nouvel espace",
            "no_workspaces" to "Aucun espace de travail",
            "settings" to "Paramètres",
            "add_column" to "Ajouter une colonne",
            "add_card" to "Ajouter une carte",
            "add" to "Ajouter",
            "new_card" to "Nouvelle carte",
            "new_column" to "Nouvelle colonne",
            "title_column" to "Titre de colonne",
            "delete" to "Supprimer",
            "edit" to "Modifier",
            "edit_card" to "Modifier la carte",
            "save" to "Enregistrer",
            "back" to "Retour",
            "theme" to "Thème",
            "theme_light" to "Clair",
            "theme_dark" to "Sombre",
            "select_folder" to "Sélectionner un dossier",
            "path_folder" to "Chemin du dossier",
            "create" to "Créer",
            "cancel" to "Annuler",
            "title" to "Titre",
            "description" to "Description",
            "difficulty" to "Difficulté",
            "color_card" to "Couleur de carte",
            "delete_column" to "Supprimer la colonne",
            "exit" to "Quitter",
            "language" to "Langue",
            "difficulty_easy" to "Facile",
            "difficulty_middle" to "Moyen",
            "difficulty_hard" to "Difficile",
            "app_name" to "Tableau de tâches",
            "welcome" to "Bienvenue",
            "loading" to "Chargement...",
            "error" to "Erreur",
            "success" to "Succès"
        ),
        "de" to mapOf(
            "workspaces" to "Arbeitsbereiche",
            "new_workspace" to "Neuer Arbeitsbereich",
            "no_workspaces" to "Keine Arbeitsbereiche",
            "settings" to "Einstellungen",
            "add_column" to "Spalte hinzufügen",
            "add_card" to "Karte hinzufügen",
            "add" to "Hinzufügen",
            "new_card" to "Neue Karte",
            "new_column" to "Neue Spalte",
            "title_column" to "Spaltentitel",
            "delete" to "Löschen",
            "edit" to "Bearbeiten",
            "edit_card" to "Karte bearbeiten",
            "save" to "Speichern",
            "back" to "Zurück",
            "theme" to "Thema",
            "theme_light" to "Hell",
            "theme_dark" to "Dunkel",
            "select_folder" to "Ordner auswählen",
            "path_folder" to "Ordnerpfad",
            "create" to "Erstellen",
            "cancel" to "Abbrechen",
            "title" to "Titel",
            "description" to "Beschreibung",
            "difficulty" to "Schwierigkeit",
            "color_card" to "Kartenfarbe",
            "delete_column" to "Spalte löschen",
            "exit" to "Beenden",
            "language" to "Sprache",
            "difficulty_easy" to "Einfach",
            "difficulty_middle" to "Mittel",
            "difficulty_hard" to "Schwer",
            "app_name" to "Aufgabenboard",
            "welcome" to "Willkommen",
            "loading" to "Wird geladen...",
            "error" to "Fehler",
            "success" to "Erfolg"
        )
    )

    fun t(key: String) = strings[locale]?.get(key) ?: key
}